In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("../data/raw/dataset.csv")

In [6]:
df.head()

,Stars,Title_of_Review,Base_Review,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,1.0 out of 5 stars,This is a ripoff. And shame on Amazon for not ...,Don't buy this product. I purchased it for my ...,NaN,NaN,NaN
1,1.0 out of 5 stars,PDF Max Pro doesn't play well with marshmallow,"Get an ""invalid file"" error since Marshmallow.",NaN,NaN,NaN
2,1.0 out of 5 stars,Worse app ever,I wouldn't even give it a one if I could. I wi...,NaN,NaN,NaN
3,1.0 out of 5 stars,I'd recommend trying to email the developer fi...,"If I could give it less stars, I would! Does n...",NaN,NaN,NaN
4,5.0 out of 5 stars,Amazing For Markup,I have several apps that can open pdf files on...,NaN,NaN,NaN

In [7]:
df.shape

(79821, 6)

In [8]:
df.columns

Index(['Stars', 'Title_of_Review', 'Base_Review', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79821 entries, 0 to 79820
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Stars            79792 non-null  object
 1   Title_of_Review  79687 non-null  object
 2   Base_Review      79488 non-null  object
 3   Unnamed: 3       10 non-null     object
 4   Unnamed: 4       10 non-null     object
 5   Unnamed: 5       0 non-null      float64
dtypes: float64(1), object(5)
memory usage: 3.7+ MB

In [10]:
df.isnull().sum()

Stars                 29
Title_of_Review      134
Base_Review          333
Unnamed: 3         79811
Unnamed: 4         79811
Unnamed: 5         79821
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(7404)

In [12]:
df["Stars"].value_counts().sort_index()

Stars
1.0 out of 5 stars    21814
2.0 out of 5 stars     5315
3.0 out of 5 stars     7712
4.0 out of 5 stars    11633
5.0 out of 5 stars    33317
a-icon-alt                1
Name: count, dtype: int64

In [13]:
df["Stars"].value_counts(normalize=True).sort_index() * 100

Stars
1.0 out of 5 stars    27.338580
2.0 out of 5 stars     6.661069
3.0 out of 5 stars     9.665129
4.0 out of 5 stars    14.579156
5.0 out of 5 stars    41.754813
a-icon-alt             0.001253
Name: proportion, dtype: float64

In [14]:
pd.set_option("display.max_colwidth", 300)

df[["Stars", "Title_of_Review", "Base_Review"]].sample(
    20,
    random_state=42
)

,Stars,Title_of_Review,Base_Review
9354,5.0 out of 5 stars,Foxgril,I love this app Whoever made this app thank you because I can call my parents and it doesn't gitch out I Will tell my friends about the app.😊
4387,3.0 out of 5 stars,Three Stars,It's good in general. But. Kind of complicated to operate
6178,3.0 out of 5 stars,It's OK,"I'm not real happy with the way the controls work. Sometimes the background color goes right over the controls, and you have no alternative but to exit. Also, I still don't know what the dropper is for. It's kind of fun to use, and not too hard once you get going."
15746,1.0 out of 5 stars,I can't use it.,I can't open this app on my blackberry passport. I tried to install for my cell phone several times. But never got this.
39247,5.0 out of 5 stars,good quality as expected,good quality as expected
19218,5.0 out of 5 stars,"Fantastic free app; not perfect, but great value and tries to keep the learning interesting and varied","For a free app, I was blown away by the value.You start by taking a sort of placement test. After that, you're introduced to the ""tree"" of available subjects, in which you focus on one part of speech or related group of words: ""Pronouns"" or ""Science"" or ""Past Present"" or ""Numbers"". These are c..."
54955,1.0 out of 5 stars,not the way to watch a premier sporting event,was a disappointment due to the constant buffering.
5414,5.0 out of 5 stars,Highly recommended,Excellent for quick reviewing of documents and light work. Highly recommended.
76349,4.0 out of 5 stars,Seems to work very well,This system works very well. Hopefully when they upgrade they won't mess it up as they have other applications.
68848,1.0 out of 5 stars,I’d be happy to pay a small fee to be able to ...,"If you’ve already cut the cord, then don’t bother with this app!I’d be happy to pay a small fee to be able to see prime time shows and things like the olympics and such. Daytime NBC could be reruns of HeeHaw for all I care, but just let us watch TV without the cable/satellite subscription!"
8449,5.0 out of 5 stars,Works on Kindle Fire HDX for a Canon,I tried every printer app to get my Canon MFP495 printer working on the Kindle. This is the only app that did it.
34358,4.0 out of 5 stars,Nice game,"Energy could build a little faster, but over all interesting."
73490,1.0 out of 5 stars,Rubbish,"The first one I watched , a small child was clutching a dog tightly. The dog looked distressed. I uninstalled it right away."
4079,5.0 out of 5 stars,Easy to use and create,"On kindle I can voice activate, correct, and build documents. I can also download other documents and fill in forms, save as pdf, and print later. Great I love it."
4026,5.0 out of 5 stars,Works great on my Droid Razor.,Works great.
53855,1.0 out of 5 stars,Don’t download it,Hot garbage. Didn’t even want to load. Couldn’t log in with my cable provider. CBS you suck.
33417,2.0 out of 5 stars,Limited,"Although the App is free, it is limited on the quantity of recipes you can store. When you reach your limit, you need to pay for an upgrade!"
12959,3.0 out of 5 stars,Three Stars,ok
74822,4.0 out of 5 stars,Works 👍,It makes my Amazon Fire Kindle work so much better! I recommend it!
62252,1.0 out of 5 stars,Not what I want it for since the update.,"Since the update, this app is worthless for me!!"

In [15]:
df_clean = df.copy()

In [16]:
df_clean = df_clean[
    ["Stars", "Title_of_Review", "Base_Review"]
].copy()

In [17]:
df_clean.shape

(79821, 3)

In [18]:
df_clean.columns = [
    "rating",
    "review_title",
    "review_text"
]

In [19]:
df_clean.columns

Index(['rating', 'review_title', 'review_text'], dtype='object')

In [20]:
df_clean["rating"] = (
    df_clean["rating"]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
)

In [21]:
df_clean["rating"] = pd.to_numeric(
    df_clean["rating"],
    errors="coerce"
)

In [22]:
df_clean["rating"].value_counts(dropna=False).sort_index()

rating
1.0    21814
2.0     5315
3.0     7712
4.0    11633
5.0    33317
NaN       30
Name: count, dtype: int64

In [23]:
df_clean["review_title"] = (
    df_clean["review_title"]
    .fillna("")
    .astype(str)
    .str.strip()
)

df_clean["review_text"] = (
    df_clean["review_text"]
    .fillna("")
    .astype(str)
    .str.strip()
)

In [24]:
df_clean["feedback"] = (
    df_clean["review_title"] + ". " +
    df_clean["review_text"]
).str.strip()

In [25]:
(df_clean["feedback"] == "").sum()

np.int64(0)

In [26]:
df_clean[
    df_clean["feedback"].str.len() < 10
][["rating", "feedback"]].head(20)

      rating   feedback
551      4.0     Ok. Ok
2975     5.0     Ok. Ok
2988     5.0    opk. ok
3000     5.0  Free. App
3002     5.0     Ok. Ok
3008     5.0   N/a. N/a
3034     5.0     Ok. Ok
3425     5.0     Ok. Ok
3551     3.0     OK. OK
3776     3.0     Ok. Ok
4819     5.0       👌. 👍
5038     1.0   Apps. OK
5107     2.0       👎. 👎
5577     5.0     Ok. Ok
5890     3.0    Fun. Ok
5937     3.0   Meh. Meh
6191     1.0   Ugh. Ugh
6206     1.0     No. No
6352     3.0     Ok. Ok
6562     5.0     Ok. Ok

In [27]:
df_clean.insert(
    0,
    "feedback_id",
    range(1, len(df_clean) + 1)
)

In [28]:
df_clean.head()

,feedback_id,rating,review_title,review_text,feedback
0,1,1.0,This is a ripoff. And shame on Amazon for not allowing a refund,Don't buy this product. I purchased it for my Amazon Kindle Fire which i recently acquired. I saw the reviews and was impressed but I failed to see the dates of the review. I downloaded the product and it does not work on my Kindle Fire (nowhere did it say it was incompatible). I have reached ou...,This is a ripoff. And shame on Amazon for not allowing a refund. Don't buy this product. I purchased it for my Amazon Kindle Fire which i recently acquired. I saw the reviews and was impressed but I failed to see the dates of the review. I downloaded the product and it does not work on my Kindle...
1,2,1.0,PDF Max Pro doesn't play well with marshmallow,"Get an ""invalid file"" error since Marshmallow.","PDF Max Pro doesn't play well with marshmallow. Get an ""invalid file"" error since Marshmallow."
2,3,1.0,Worse app ever,I wouldn't even give it a one if I could. I will not even put documents or PDF books in library. I would appreciate my money back. It won't open anything. This may cause me to go back to Barnes and Noble.,Worse app ever. I wouldn't even give it a one if I could. I will not even put documents or PDF books in library. I would appreciate my money back. It won't open anything. This may cause me to go back to Barnes and Noble.
3,4,1.0,I'd recommend trying to email the developer first to ensure you ...,"If I could give it less stars, I would! Does not work on Samsung Galaxy Note 8. Email to developer does not work. Not updated since Dec 2015 and they are still collecting money!!! Many others with the same complaint. If you risk buying this program, I'd recommend trying to email the developer fi...","I'd recommend trying to email the developer first to ensure you .... If I could give it less stars, I would! Does not work on Samsung Galaxy Note 8. Email to developer does not work. Not updated since Dec 2015 and they are still collecting money!!! Many others with the same complaint. If you ris..."
4,5,5.0,Amazing For Markup,"I have several apps that can open pdf files on my device, from an ebook reader to an office app, so I was not sure why I would need another pdf reader. When this app popped as the FAOTD though I figured I would try it out; I am extremely impressed.The app really stands out on two fronts: TTS le...","Amazing For Markup. I have several apps that can open pdf files on my device, from an ebook reader to an office app, so I was not sure why I would need another pdf reader. When this app popped as the FAOTD though I figured I would try it out; I am extremely impressed.The app really stands out on..."

In [31]:
df_clean.to_csv(
    "../data/processed/feedback_cleaned.csv",
    index=False
)

In [32]:
short_feedback = df_clean[
    df_clean["feedback"].str.len() < 20
]

len(short_feedback)

5281

In [33]:
len(short_feedback) / len(df_clean) * 100

6.61605341952619

In [34]:
duplicate_rows = df_clean[
    df_clean.duplicated(
        subset=["rating", "review_title", "review_text"],
        keep=False
    )
].sort_values("review_text")

In [35]:
duplicate_rows[
    ["rating", "review_title", "review_text"]
].head(30)

       rating                 review_title review_text
42257     5.0  Translate review to English
25633     5.0  Translate review to English
42343     2.0  Translate review to English
42341     1.0  Translate review to English
66470     NaN
66469     NaN
66468     NaN
66467     NaN
66466     NaN
66465     NaN
66464     NaN
66463     NaN
66462     NaN
66461     NaN
66460     NaN
42340     4.0  Translate review to English
66459     NaN
66458     NaN
66457     NaN
66456     NaN
25634     5.0  Translate review to English
42347     1.0  Translate review to English
25635     4.0  Translate review to English
42353     1.0  Translate review to English
42376     1.0  Translate review to English
25653     1.0  Translate review to English
18511     3.0  Translate review to English
42364     3.0  Translate review to English
25650     5.0  Translate review to English
25649     4.0  Translate review to English

In [36]:
df_clean["feedback"].nunique()

72199

In [37]:
df_clean["feedback"].duplicated().sum()

np.int64(7622)

In [38]:
df_clean["feedback"].value_counts().head(20)

feedback
Translate review to English.                 260
Report abuse. Translate review to English    226
Good. Good                                   195
Ok. Ok                                       137
Five Stars. Great                            124
Great. Great                                 115
Five Stars. Good                              95
Three Stars. ok                               85
Five Stars. great                             69
Five Stars. good                              64
Five Stars. Love it                           60
.                                             53
Three Stars. Ok                               48
Five Stars. Ok                                44
Five Stars. Excellent                         42
Four Stars. Good                              41
Five Stars. Awesome                           40
Five Stars. Works great                       37
No. No                                        36
Five Stars. Love it!                          34
Name: count, dtype: int64

In [39]:
duplicate_rows = df_clean[
    df_clean.duplicated(
        subset=["rating", "review_title", "review_text"],
        keep=False
    )
].sort_values("review_text")

duplicate_rows[
    ["rating", "review_title", "review_text"]
].head(30)

       rating                 review_title review_text
42257     5.0  Translate review to English
25633     5.0  Translate review to English
42343     2.0  Translate review to English
42341     1.0  Translate review to English
66470     NaN
66469     NaN
66468     NaN
66467     NaN
66466     NaN
66465     NaN
66464     NaN
66463     NaN
66462     NaN
66461     NaN
66460     NaN
42340     4.0  Translate review to English
66459     NaN
66458     NaN
66457     NaN
66456     NaN
25634     5.0  Translate review to English
42347     1.0  Translate review to English
25635     4.0  Translate review to English
42353     1.0  Translate review to English
42376     1.0  Translate review to English
25653     1.0  Translate review to English
18511     3.0  Translate review to English
42364     3.0  Translate review to English
25650     5.0  Translate review to English
25649     4.0  Translate review to English

In [40]:
df_clean["is_source_artifact"] = (
    df_clean["feedback"]
    .str.lower()
    .str.strip()
    .isin([
        "translate review to english.",
        "report abuse. translate review to english",
        "."
    ])
)

In [41]:
df_clean["is_source_artifact"].value_counts()

is_source_artifact
False    79282
True       539
Name: count, dtype: int64

In [42]:
low_info_patterns = [
    "ok",
    "ok. ok",
    "good",
    "good. good",
    "great",
    "great. great",
    "awesome",
    "excellent",
    "love it",
    "no",
    "no. no",
    "n/a",
    "n/a. n/a",
    "ugh",
    "ugh. ugh"
]

In [43]:
df_clean["is_low_information"] = (
    df_clean["feedback"]
    .str.lower()
    .str.strip()
    .isin(low_info_patterns)
)

In [44]:
df_clean["is_low_information"].value_counts()

is_low_information
False    79224
True       597
Name: count, dtype: int64

In [45]:
df_clean["is_usable_feedback"] = (
    ~df_clean["is_source_artifact"]
    & ~df_clean["is_low_information"]
    & (df_clean["feedback"].str.len() >= 10)
)

In [46]:
df_clean["is_usable_feedback"].value_counts()

is_usable_feedback
True     78390
False     1431
Name: count, dtype: int64

In [47]:
df_clean.groupby("is_usable_feedback")["feedback"].count()

is_usable_feedback
False     1431
True     78390
Name: feedback, dtype: int64

In [48]:
df_clean[
    ~df_clean["is_usable_feedback"]
][
    ["rating", "feedback", "is_source_artifact", "is_low_information"]
].head(50)

,rating,feedback,is_source_artifact,is_low_information
192,1.0,Report abuse. Translate review to English,True,False
551,4.0,Ok. Ok,False,True
575,5.0,Report abuse. Translate review to English,True,False
662,5.0,good. good,False,True
2975,5.0,Ok. Ok,False,True
2988,5.0,opk. ok,False,False
3000,5.0,Free. App,False,False
3002,5.0,Ok. Ok,False,True
3008,5.0,N/a. N/a,False,True
3015,5.0,Report abuse. Translate review to English,True,False
3027,4.0,Report abuse. Translate review to English,True,False
3034,5.0,Ok. Ok,False,True
3039,5.0,good. good,False,True
3071,5.0,Report abuse. Translate review to English,True,False
3142,4.0,Good. Good,False,True
3150,5.0,Report abuse. Translate review to English,True,False
3271,5.0,Report abuse. Translate review to English,True,False
3304,5.0,Great. Great,False,True
3307,5.0,Great. Great,False,True
3334,4.0,Report abuse. Translate review to English,True,False
3352,5.0,Good. Good,False,True
3425,5.0,Ok. Ok,False,True
3524,5.0,Report abuse. Translate review to English,True,False
3551,3.0,OK. OK,False,True
3658,4.0,Great. Great,False,True
3680,5.0,Good. Good,False,True
3776,3.0,Ok. Ok,False,True
4162,5.0,good. Good,False,True
4334,4.0,Good. Good,False,True
4733,3.0,good. Good,False,True
4819,5.0,👌. 👍,False,False
5038,1.0,Apps. OK,False,False
5081,3.0,Good. Good,False,True
5107,2.0,👎. 👎,False,False
5509,5.0,Report abuse. Translate review to English,True,False
5570,5.0,Great. Great,False,True
5577,5.0,Ok. Ok,False,True
5580,5.0,Good. Good,False,True
5584,5.0,Good. Good,False,True
5592,5.0,Report abuse. Translate review to English,True,False
5890,3.0,Fun. Ok,False,False
5937,3.0,Meh. Meh,False,False
6077,5.0,Great. Great,False,True
6191,1.0,Ugh. Ugh,False,True
6206,1.0,No. No,False,True
6334,4.0,Good. Good,False,True
6337,4.0,Translate review to English.,True,False
6338,5.0,Translate review to English.,True,False
6339,5.0,Translate review to English.,True,False
6340,3.0,Translate review to English.,True,False

In [51]:
df_clean.to_csv(
    "../data/processed/feedback_cleaned.csv",
    index=False
)

In [52]:
df_clean["text_for_ai"] = (
    df_clean["review_title"].fillna("") + " " +
    df_clean["review_text"].fillna("")
).str.strip()

In [53]:
rating_title_pattern = r"^(one|two|three|four|five)\s+stars?$"

df_clean["clean_title"] = (
    df_clean["review_title"]
    .str.strip()
)

df_clean.loc[
    df_clean["clean_title"].str.lower().str.match(
        rating_title_pattern,
        na=False
    ),
    "clean_title"
] = ""

In [54]:
df_clean["text_for_ai"] = (
    df_clean["clean_title"] + " " +
    df_clean["review_text"]
).str.strip()

In [55]:
df_clean.to_csv(
    "../data/processed/feedback_cleaned.csv",
    index=False
)

In [56]:
df_clean.shape

(79821, 10)

In [57]:
df_clean[[
    "rating",
    "review_title",
    "clean_title",
    "review_text",
    "text_for_ai"
]].sample(10, random_state=42)

,rating,review_title,clean_title,review_text,text_for_ai
9354,5.0,Foxgril,Foxgril,I love this app Whoever made this app thank you because I can call my parents and it doesn't gitch out I Will tell my friends about the app.😊,Foxgril I love this app Whoever made this app thank you because I can call my parents and it doesn't gitch out I Will tell my friends about the app.😊
4387,3.0,Three Stars,,It's good in general. But. Kind of complicated to operate,It's good in general. But. Kind of complicated to operate
6178,3.0,It's OK,It's OK,"I'm not real happy with the way the controls work. Sometimes the background color goes right over the controls, and you have no alternative but to exit. Also, I still don't know what the dropper is for. It's kind of fun to use, and not too hard once you get going.","It's OK I'm not real happy with the way the controls work. Sometimes the background color goes right over the controls, and you have no alternative but to exit. Also, I still don't know what the dropper is for. It's kind of fun to use, and not too hard once you get going."
15746,1.0,I can't use it.,I can't use it.,I can't open this app on my blackberry passport. I tried to install for my cell phone several times. But never got this.,I can't use it. I can't open this app on my blackberry passport. I tried to install for my cell phone several times. But never got this.
39247,5.0,good quality as expected,good quality as expected,good quality as expected,good quality as expected good quality as expected
19218,5.0,"Fantastic free app; not perfect, but great value and tries to keep the learning interesting and varied","Fantastic free app; not perfect, but great value and tries to keep the learning interesting and varied","For a free app, I was blown away by the value.You start by taking a sort of placement test. After that, you're introduced to the ""tree"" of available subjects, in which you focus on one part of speech or related group of words: ""Pronouns"" or ""Science"" or ""Past Present"" or ""Numbers"". These are c...","Fantastic free app; not perfect, but great value and tries to keep the learning interesting and varied For a free app, I was blown away by the value.You start by taking a sort of placement test. After that, you're introduced to the ""tree"" of available subjects, in which you focus on one part of..."
54955,1.0,not the way to watch a premier sporting event,not the way to watch a premier sporting event,was a disappointment due to the constant buffering.,not the way to watch a premier sporting event was a disappointment due to the constant buffering.
5414,5.0,Highly recommended,Highly recommended,Excellent for quick reviewing of documents and light work. Highly recommended.,Highly recommended Excellent for quick reviewing of documents and light work. Highly recommended.
76349,4.0,Seems to work very well,Seems to work very well,This system works very well. Hopefully when they upgrade they won't mess it up as they have other applications.,Seems to work very well This system works very well. Hopefully when they upgrade they won't mess it up as they have other applications.
68848,1.0,I’d be happy to pay a small fee to be able to ...,I’d be happy to pay a small fee to be able to ...,"If you’ve already cut the cord, then don’t bother with this app!I’d be happy to pay a small fee to be able to see prime time shows and things like the olympics and such. Daytime NBC could be reruns of HeeHaw for all I care, but just let us watch TV without the cable/satellite subscription!","I’d be happy to pay a small fee to be able to ... If you’ve already cut the cord, then don’t bother with this app!I’d be happy to pay a small fee to be able to see prime time shows and things like the olympics and such. Daytime NBC could be reruns of HeeHaw for all I care, but just let us watch ..."

In [58]:
eval_df = df_clean[
    df_clean["is_usable_feedback"]
].sample(
    200,
    random_state=42
).copy()

In [59]:
eval_df.shape

(200, 10)

In [60]:
eval_df[
    [
        "feedback_id",
        "rating",
        "text_for_ai"
    ]
].head(20)

,feedback_id,rating,text_for_ai
52580,52581,1.0,works for 20 seconds then crashes have to restart useless works for 20 seconds then crashes. then you have to restart it for another 20 second view. not very encourragedbfo get the pro model.
33250,33251,5.0,Great I like this app i like a lot i really really do. It is my favorite app. it really really is. These questionnaires are annoying.
50175,50176,5.0,awesome Awesome I hope it.will be awesome
32076,32077,5.0,Great Easy to save. Easy to use. Great recipes.
72435,72436,1.0,Not worth it Only able to use if you have a paid subscriber. If you just use internet tv it won't work.
705,706,1.0,False advertising ? I download this app to my Kindle Fire HD. I tried to print and it would not let me print unless I upgraded to paying for the app.
33787,33788,5.0,"enjoyable I've played games like this before, they're fun and easy to play."
57584,57585,4.0,Good app Good app
70106,70107,1.0,It said it worked with amazon fire but would not play
72864,72865,5.0,My dog loves this! Best thing ever for remote working dog-parents who can’t keep playing tug-of-war all day.
2652,2653,1.0,Install FAILED Does not work.
3230,3231,5.0,Fantastic app for my kindle I use this on my kindle. Couldn't keep track of my inventory without it.
22593,22594,5.0,"The Best This app is Amazing! It is awesome, I definitely recommend it!"
6916,6917,5.0,Works great
5965,5966,4.0,"Quite fun though. Can't wait for the artist in the ... A little hard to use for me, but then I'm not artistically inclined. Quite fun though. Can't wait for the artist in the family to try it out."
67938,67939,5.0,"Bought for the Le Tour de France What a great streaming service! Streamed it at my cabin through a hot spot on my cell phone with Amazon TV worked great!!! Very happy. With WIFI at home easy set up never glitches, would recommend."
35483,35484,1.0,Cradle of empire Didn't like the game at all
64005,64006,1.0,Not ordered or purchased Did not order don’t know anything about it
39765,39766,5.0,Good MMO game
21057,21058,5.0,"Fantastic free app! It is easy, you are able to revisit lessons any time, and it sounds out the words.I like that you hear it, see it, plus must translate from Spanish to English and from English to Spanish."

In [61]:
eval_df[
    [
        "feedback_id",
        "rating",
        "text_for_ai"
    ]
].to_csv(
    "../data/eval/eval_set.csv",
    index=False
)

In [62]:
eval_df = df_clean[
    df_clean["is_usable_feedback"]
].sample(
    200,
    random_state=42
).copy()

In [63]:
eval_df[
    [
        "feedback_id",
        "rating",
        "text_for_ai"
    ]
].to_csv(
    "../data/eval/eval_set.csv",
    index=False
)

In [64]:
eval_df.shape

(200, 10)

In [65]:
eval_df[
    ["feedback_id", "rating", "text_for_ai"]
].head(10)

,feedback_id,rating,text_for_ai
52580,52581,1.0,works for 20 seconds then crashes have to restart useless works for 20 seconds then crashes. then you have to restart it for another 20 second view. not very encourragedbfo get the pro model.
33250,33251,5.0,Great I like this app i like a lot i really really do. It is my favorite app. it really really is. These questionnaires are annoying.
50175,50176,5.0,awesome Awesome I hope it.will be awesome
32076,32077,5.0,Great Easy to save. Easy to use. Great recipes.
72435,72436,1.0,Not worth it Only able to use if you have a paid subscriber. If you just use internet tv it won't work.
705,706,1.0,False advertising ? I download this app to my Kindle Fire HD. I tried to print and it would not let me print unless I upgraded to paying for the app.
33787,33788,5.0,"enjoyable I've played games like this before, they're fun and easy to play."
57584,57585,4.0,Good app Good app
70106,70107,1.0,It said it worked with amazon fire but would not play
72864,72865,5.0,My dog loves this! Best thing ever for remote working dog-parents who can’t keep playing tug-of-war all day.

In [66]:
eval_df["gold_sentiment"] = ""
eval_df["gold_intent"] = ""
eval_df["gold_product_area"] = ""
eval_df["gold_theme"] = ""
eval_df["gold_severity"] = ""

In [67]:
eval_df[
    [
        "feedback_id",
        "text_for_ai",
        "gold_sentiment",
        "gold_intent",
        "gold_product_area",
        "gold_theme",
        "gold_severity"
    ]
].to_csv(
    "../data/eval/eval_set.csv",
    index=False
)

In [68]:
SENTIMENTS = [
    "positive",
    "neutral",
    "negative",
    "mixed"
]

INTENTS = [
    "complaint",
    "bug_report",
    "feature_request",
    "praise",
    "question",
    "pricing_feedback",
    "comparison",
    "other"
]

PRODUCT_AREAS = [
    "performance",
    "reliability",
    "usability",
    "features",
    "ui_ux",
    "pricing",
    "content",
    "compatibility",
    "account",
    "support",
    "notifications",
    "other"
]

SEVERITIES = [
    "low",
    "medium",
    "high",
    "critical"
]

In [69]:
AI_COLUMNS = [
    "sentiment",
    "intent",
    "product_area",
    "theme",
    "severity",
    "actionability",
    "confidence",
    "evidence"
]

In [70]:
ACTIONABILITY = [
    "low",
    "medium",
    "high"
]

In [71]:
eval_df[
    [
        "feedback_id",
        "rating",
        "text_for_ai"
    ]
].head(20).to_string(index=False)

" feedback_id  rating                                                                                                                                                                                                                            text_for_ai\n       52581     1.0                                      works for 20 seconds then crashes\xa0 have to restart\xa0 useless works for 20 seconds then crashes. then you have to restart it for another 20 second view. not very encourragedbfo get the pro model.\n       33251     5.0                                                                                                 Great I like this app i like a lot i really really do. It is my favorite app. it really really is.\xa0 These questionnaires are annoying.\n       50176     5.0                                                                                                                                                                                              awesome Awesome I hope it.will be awesome\n       32077     5.0                                                                                                                                                                                        Great Easy to save. Easy to use. Great recipes.\n       72436     1.0                                                                                                                                Not worth it Only able to use if you have a paid subscriber. If you just use internet tv it won't work.\n         706     1.0                                                                                  False advertising ? I download this app to my Kindle Fire HD. I tried to print and it would not let me print unless I upgraded to paying for the app.\n       33788     5.0                                                                                                                                                            enjoyable I've played games like this before, they're fun and easy to play.\n       57585     4.0                                                                                                                                                                                                                      Good app Good app\n       70107     1.0                                                                                                                                                                                  It said it worked with amazon fire but would not play\n       72865     5.0                                                                                                                           My dog loves this! Best thing ever for remote working dog-parents who can’t keep playing tug-of-war all day.\n        2653     1.0                                                                                                                                                                                                          Install FAILED Does not work.\n        3231     5.0                                                                                                                                   Fantastic app for my kindle I use this on my kindle. Couldn't keep track of my inventory without it.\n       22594     5.0                                                                                                                                                                The Best This app is Amazing! It is awesome, I definitely recommend it!\n        6917     5.0                                                                                                                                                                                                                            Works great\n        5966     4.0                                   Quite fun though. Can't wait for the artist in the ... A little hard to use for me, but then I'm not artistically inclined. Quite fun though. Can't wait for the artist in the family to try it out.\n       67939     5.0 Bought for the Le Tour de France What a great streaming service! Streamed it at my cabin through a hot spot on my cell phone with Amazon TV worked great!!! Very happy. With WIFI at home easy set up never glitches, would recommend.\n       35484     1.0                                                                                                                                                                                           Cradle of empire Didn't like the game at all\n       64006     1.0                                                                                                                                                                    Not ordered or purchased Did not order don’t know anything about it\n       39766     5.0                                                                                                                                                                                                                          Good MMO game\n       21058     5.0                        Fantastic free app! It is easy, you are able to revisit lessons any time, and it sounds out the words.I like that you hear it, see it, plus must translate from Spanish to English and from English to Spanish."

In [72]:
labels = {
    52581: ["negative", "bug_report", "reliability", "App crashes repeatedly", "high", "high"],
    33251: ["mixed", "complaint", "features", "Annoying questionnaires", "medium", "high"],
    50176: ["positive", "praise", "other", "General satisfaction", "low", "low"],
    32077: ["positive", "praise", "usability", "Easy recipe management", "low", "medium"],
    72436: ["negative", "pricing_feedback", "pricing", "Paid subscription required", "high", "high"],
    706: ["negative", "pricing_feedback", "pricing", "Printing locked behind upgrade", "high", "high"],
    33788: ["positive", "praise", "other", "Fun and easy gameplay", "low", "low"],
    57585: ["positive", "praise", "other", "General satisfaction", "low", "low"],
    70107: ["negative", "bug_report", "compatibility", "Amazon Fire compatibility failure", "high", "high"],
    72865: ["positive", "praise", "features", "Product solves remote-working use case", "low", "medium"],
    2653: ["negative", "bug_report", "reliability", "Installation failure", "high", "high"],
    3231: ["positive", "praise", "compatibility", "Useful Kindle experience", "low", "medium"],
    22594: ["positive", "praise", "other", "Strong overall satisfaction", "low", "low"],
    6917: ["positive", "praise", "other", "Works as expected", "low", "low"],
    5966: ["mixed", "complaint", "usability", "Difficult to use for beginners", "medium", "high"],
    67939: ["positive", "praise", "reliability", "Reliable streaming and setup", "low", "medium"],
    35484: ["negative", "complaint", "features", "Dislike of game experience", "medium", "medium"],
    64006: ["neutral", "other", "account", "Unknown/unrecognized purchase", "medium", "high"],
    39766: ["positive", "praise", "other", "Enjoyable MMO experience", "low", "low"],
    21058: ["positive", "praise", "usability", "Easy and effective language learning", "low", "medium"]
}

In [73]:
for feedback_id, values in labels.items():
    (
        sentiment,
        intent,
        product_area,
        theme,
        severity,
        actionability
    ) = values

    eval_df.loc[
        eval_df["feedback_id"] == feedback_id,
        [
            "gold_sentiment",
            "gold_intent",
            "gold_product_area",
            "gold_theme",
            "gold_severity"
        ]
    ] = [
        sentiment,
        intent,
        product_area,
        theme,
        severity
    ]

In [74]:
eval_df["gold_actionability"] = ""

In [75]:
for feedback_id, values in labels.items():
    eval_df.loc[
        eval_df["feedback_id"] == feedback_id,
        "gold_actionability"
    ] = values[5]

In [76]:
eval_df.to_csv(
    "../data/eval/eval_set.csv",
    index=False
)

In [77]:
eval_df[
    [
        "feedback_id",
        "gold_sentiment",
        "gold_intent",
        "gold_product_area",
        "gold_theme",
        "gold_severity",
        "gold_actionability"
    ]
].head(20)

,feedback_id,gold_sentiment,gold_intent,gold_product_area,gold_theme,gold_severity,gold_actionability
52580,52581,negative,bug_report,reliability,App crashes repeatedly,high,high
33250,33251,mixed,complaint,features,Annoying questionnaires,medium,high
50175,50176,positive,praise,other,General satisfaction,low,low
32076,32077,positive,praise,usability,Easy recipe management,low,medium
72435,72436,negative,pricing_feedback,pricing,Paid subscription required,high,high
705,706,negative,pricing_feedback,pricing,Printing locked behind upgrade,high,high
33787,33788,positive,praise,other,Fun and easy gameplay,low,low
57584,57585,positive,praise,other,General satisfaction,low,low
70106,70107,negative,bug_report,compatibility,Amazon Fire compatibility failure,high,high
72864,72865,positive,praise,features,Product solves remote-working use case,low,medium
2652,2653,negative,bug_report,reliability,Installation failure,high,high
3230,3231,positive,praise,compatibility,Useful Kindle experience,low,medium
22593,22594,positive,praise,other,Strong overall satisfaction,low,low
6916,6917,positive,praise,other,Works as expected,low,low
5965,5966,mixed,complaint,usability,Difficult to use for beginners,medium,high
67938,67939,positive,praise,reliability,Reliable streaming and setup,low,medium
35483,35484,negative,complaint,features,Dislike of game experience,medium,medium
64005,64006,neutral,other,account,Unknown/unrecognized purchase,medium,high
39765,39766,positive,praise,other,Enjoyable MMO experience,low,low
21057,21058,positive,praise,usability,Easy and effective language learning,low,medium

In [78]:
import sys
print(sys.executable)

/Users/aaa/Documents/voice-of-customer-copilot/.venv/bin/python3

In [79]:
import openai

print(openai.__version__)

2.48.0

In [80]:
import sys

print(sys.executable)

/Users/aaa/Documents/voice-of-customer-copilot/.venv/bin/python3

In [84]:
import os
from pathlib import Path
from dotenv import load_dotenv

env_path = Path.home() / "Documents" / "voice-of-customer-copilot" / ".env"

print(".env exists:", env_path.exists())

loaded = load_dotenv(dotenv_path=env_path, override=True)
api_key = os.getenv("OPENAI_API_KEY")

print(".env loaded:", loaded)
print("API key loaded:", bool(api_key))

.env exists: True
.env loaded: True
API key loaded: True

In [85]:
from openai import OpenAI

client = OpenAI()

print("OpenAI client created successfully")

OpenAI client created successfully

In [86]:
SYSTEM_PROMPT = """
You are a Voice-of-Customer analysis assistant for a product team.

Your job is to analyze customer feedback and extract structured,
actionable information.

You MUST follow these rules:

1. Analyze only the information explicitly contained in the review.
2. Do not invent facts, causes, features, or customer motivations.
3. If the review does not provide enough information, choose "other"
   or use a lower confidence score.
4. Choose exactly one value for each categorical field.
5. The theme should be a short, specific description of the main
   customer issue, need, or positive experience.
6. Evidence must be a short exact quote copied from the review.
7. Do not use information from the star rating to invent claims
   that are not present in the text.
8. Severity should reflect the impact described by the customer,
   not simply the star rating.
9. Actionability should reflect whether a product team could
   reasonably take a concrete action based on the feedback.
10. Confidence must be between 0 and 1.

Allowed sentiment values:
- positive
- neutral
- negative
- mixed

Allowed intent values:
- complaint
- bug_report
- feature_request
- praise
- question
- pricing_feedback
- comparison
- other

Allowed product_area values:
- performance
- reliability
- usability
- features
- ui_ux
- pricing
- content
- compatibility
- account
- support
- notifications
- other

Allowed severity values:
- low
- medium
- high
- critical

Allowed actionability values:
- low
- medium
- high
"""

In [87]:
OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "sentiment": {
            "type": "string",
            "enum": SENTIMENTS
        },
        "intent": {
            "type": "string",
            "enum": INTENTS
        },
        "product_area": {
            "type": "string",
            "enum": PRODUCT_AREAS
        },
        "theme": {
            "type": "string"
        },
        "severity": {
            "type": "string",
            "enum": SEVERITIES
        },
        "actionability": {
            "type": "string",
            "enum": ACTIONABILITY
        },
        "confidence": {
            "type": "number",
            "minimum": 0,
            "maximum": 1
        },
        "evidence": {
            "type": "string"
        }
    },
    "required": [
        "sentiment",
        "intent",
        "product_area",
        "theme",
        "severity",
        "actionability",
        "confidence",
        "evidence"
    ],
    "additionalProperties": False
}

In [88]:
test_review = eval_df[
    eval_df["feedback_id"] == 52581
]["text_for_ai"].iloc[0]

print(test_review)

works for 20 seconds then crashes  have to restart  useless works for 20 seconds then crashes. then you have to restart it for another 20 second view. not very encourragedbfo get the pro model.